view: fact_customer_transaction_summarize {
# FACT_CUSTOMER_TRANSACTION
# PK, FK  DATE_CD DATETIME
# PK, FK  CUSTOMER_CD STRING
# PK, FK  PRODUCT_CD  STRING
# PK, FK  STORE_CD  STRING
#   ITEMS STRING
#   CHANNEL_CD  STRING
#   PURCHASE_VALUE_BEFORE_TAX FLOAT
#   ORDERS_COUNT  INTEGER
#   CURRENT_YEAR_YTD_VALUE  FLOAT
#   LAST_YEAR_YTD_VALUE FLOAT
#   TRANSACTION_PROFIT_VALUE  FLOAT

}
